package com.hpdxay.xmly.entitis;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BULLET_ENTITY".
 */
public class BulletEntity {

    private Long trackId;
    private String title;
    private String coverMiddle;
    private String tags;
    private String playPath32;
    private String playPath64;
    private Integer albumId;
    private String albumTitle;
    private Integer favoritesCounts;
    private Integer playsCounts;
    private Integer commentsCounts;
    private Integer sharesCounts;

    public BulletEntity() {
    }

    public BulletEntity(Long trackId) {
        this.trackId = trackId;
    }

    public BulletEntity(Long trackId, String title, String coverMiddle, String tags, String playPath32, String playPath64, Integer albumId, String albumTitle, Integer favoritesCounts, Integer playsCounts, Integer commentsCounts, Integer sharesCounts) {
        this.trackId = trackId;
        this.title = title;
        this.coverMiddle = coverMiddle;
        this.tags = tags;
        this.playPath32 = playPath32;
        this.playPath64 = playPath64;
        this.albumId = albumId;
        this.albumTitle = albumTitle;
        this.favoritesCounts = favoritesCounts;
        this.playsCounts = playsCounts;
        this.commentsCounts = commentsCounts;
        this.sharesCounts = sharesCounts;
    }

    public Long getTrackId() {
        return trackId;
    }

    public void setTrackId(Long trackId) {
        this.trackId = trackId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCoverMiddle() {
        return coverMiddle;
    }

    public void setCoverMiddle(String coverMiddle) {
        this.coverMiddle = coverMiddle;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getPlayPath32() {
        return playPath32;
    }

    public void setPlayPath32(String playPath32) {
        this.playPath32 = playPath32;
    }

    public String getPlayPath64() {
        return playPath64;
    }

    public void setPlayPath64(String playPath64) {
        this.playPath64 = playPath64;
    }

    public Integer getAlbumId() {
        return albumId;
    }

    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    public String getAlbumTitle() {
        return albumTitle;
    }

    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }

    public Integer getFavoritesCounts() {
        return favoritesCounts;
    }

    public void setFavoritesCounts(Integer favoritesCounts) {
        this.favoritesCounts = favoritesCounts;
    }

    public Integer getPlaysCounts() {
        return playsCounts;
    }

    public void setPlaysCounts(Integer playsCounts) {
        this.playsCounts = playsCounts;
    }

    public Integer getCommentsCounts() {
        return commentsCounts;
    }

    public void setCommentsCounts(Integer commentsCounts) {
        this.commentsCounts = commentsCounts;
    }

    public Integer getSharesCounts() {
        return sharesCounts;
    }

    public void setSharesCounts(Integer sharesCounts) {
        this.sharesCounts = sharesCounts;
    }

}
